## EX. 1

In [2]:
import numpy as np

def zeroMean(dataMat):      
    meanVal=np.mean(dataMat,axis=0)     #按列求均值，即求各个特征的均值
    newData=dataMat-meanVal
    return newData,meanVal

def pca(dataMat,n):
    newData,meanVal=zeroMean(dataMat)
    print(newData)
    print('mean_vector', meanVal, '\n')
    # newData = dataMat
    covMat=np.cov(newData,rowvar=0)    #求协方差矩阵,return ndarray；若rowvar非0，一列代表一个样本，为0，一行代表一个样本
    
    eigVals,eigVects=np.linalg.eig(np.mat(covMat))#求特征值和特征向量,特征向量是按列放的，即一列代表一个特征向量
    print('eigenvalues:', eigVals,'\n')
    print('eigenvectors:',eigVects, '\n')
    eigValIndice=np.argsort(eigVals)            #对特征值从小到大排序
    n_eigValIndice=eigValIndice[-1:-(n+1):-1]   #最大的n个特征值的下标
    n_eigVect=eigVects[:,n_eigValIndice]        #最大的n个特征值对应的特征向量
    for i in n_eigValIndice:
        print('the', i+1, 'st', 'eigenvalue is: ', eigVals[i],'\n')
        print('the', i+1, 'st', 'eigenvector is: ',eigVects[:,i], '\n' )
    # lowDDataMat=newData*n_eigVect               #低维特征空间的数据
    # reconMat=(lowDDataMat*n_eigVect.T)+meanVal  #重构数据
    # return lowDDataMat,reconMat
    return n_eigValIndice, n_eigVect

In [4]:
data = np.array([[3,1,1],[6.5,1,1.5],[5.5,3,2.5],[0.5,-1,-0.5],[-0.5,1,0.5]])
print(data, '\n')
pca(data, 2)

[[ 3.   1.   1. ]
 [ 6.5  1.   1.5]
 [ 5.5  3.   2.5]
 [ 0.5 -1.  -0.5]
 [-0.5  1.   0.5]] 

[[ 0.   0.   0. ]
 [ 3.5  0.   0.5]
 [ 2.5  2.   1.5]
 [-2.5 -2.  -1.5]
 [-3.5  0.  -0.5]]
mean_vector [3. 1. 1.] 

eigenvalues: [1.10000000e+01 1.50000000e+00 1.84339738e-16] 

eigenvectors: [[ 0.90453403  0.40824829 -0.12309149]
 [ 0.30151134 -0.81649658 -0.49236596]
 [ 0.30151134 -0.40824829  0.86164044]] 

the 1 st eigenvalue is:  11.000000000000002 

the 1 st eigenvector is:  [[0.90453403]
 [0.30151134]
 [0.30151134]] 

the 2 st eigenvalue is:  1.500000000000002 

the 2 st eigenvector is:  [[ 0.40824829]
 [-0.81649658]
 [-0.40824829]] 



(array([0, 1], dtype=int64), matrix([[ 0.90453403,  0.40824829],
         [ 0.30151134, -0.81649658],
         [ 0.30151134, -0.40824829]]))