## EX. 1

In [1]:
import numpy as np

def zeroMean(dataMat):      
    meanVal=np.mean(dataMat,axis=0)     #按列求均值，即求各个特征的均值
    newData=dataMat-meanVal
    return newData,meanVal

def pca(dataMat,n):
    newData,meanVal=zeroMean(dataMat)
    print(newData)
    print('mean_vector', meanVal, '\n')
    # newData = dataMat
    covMat=np.cov(newData,rowvar=0)    #求协方差矩阵,return ndarray；若rowvar非0，一列代表一个样本，为0，一行代表一个样本
    
    eigVals,eigVects=np.linalg.eig(np.mat(covMat))#求特征值和特征向量,特征向量是按列放的，即一列代表一个特征向量
    print('eigenvalues:', eigVals,'\n')
    print('eigenvectors:',eigVects, '\n')
    eigValIndice=np.argsort(eigVals)            #对特征值从小到大排序
    n_eigValIndice=eigValIndice[-1:-(n+1):-1]   #最大的n个特征值的下标
    n_eigVect=eigVects[:,n_eigValIndice]        #最大的n个特征值对应的特征向量
    for i in n_eigValIndice:
        print('the', i+1, 'st', 'eigenvalue is: ', eigVals[i],'\n')
        print('the', i+1, 'st', 'eigenvector is: ',eigVects[:,i], '\n' )
    # lowDDataMat=newData*n_eigVect               #低维特征空间的数据
    # reconMat=(lowDDataMat*n_eigVect.T)+meanVal  #重构数据
    # return lowDDataMat,reconMat
    return n_eigValIndice, n_eigVect

In [2]:
data = np.array([[3,1,1],[6.5,1,1.5],[5.5,3,2.5],[0.5,-1,-0.5],[-0.5,1,0.5]])
print(data, '\n')
pca(data, 2)

[[ 3.   1.   1. ]
 [ 6.5  1.   1.5]
 [ 5.5  3.   2.5]
 [ 0.5 -1.  -0.5]
 [-0.5  1.   0.5]] 

[[ 0.   0.   0. ]
 [ 3.5  0.   0.5]
 [ 2.5  2.   1.5]
 [-2.5 -2.  -1.5]
 [-3.5  0.  -0.5]]
mean_vector [3. 1. 1.] 

eigenvalues: [1.10000000e+01 1.50000000e+00 1.84339738e-16] 

eigenvectors: [[ 0.90453403  0.40824829 -0.12309149]
 [ 0.30151134 -0.81649658 -0.49236596]
 [ 0.30151134 -0.40824829  0.86164044]] 

the 1 st eigenvalue is:  11.000000000000002 

the 1 st eigenvector is:  [[0.90453403]
 [0.30151134]
 [0.30151134]] 

the 2 st eigenvalue is:  1.500000000000002 

the 2 st eigenvector is:  [[ 0.40824829]
 [-0.81649658]
 [-0.40824829]] 



(array([0, 1], dtype=int64), matrix([[ 0.90453403,  0.40824829],
         [ 0.30151134, -0.81649658],
         [ 0.30151134, -0.40824829]]))

## EX. 3

### a)

In [3]:
# power iteration method
import numpy as np
def power_iteration (A, num_simulations ):
 # Ideally choose a random vector
 # To decrease the chance that our vector
 # Is orthogonal to the eigenvector
 b_k = np.ones(A.shape[0])/ np.sqrt(A.shape[0])
 print('init eigenvector:', b_k,'\n')
 for _ in range(num_simulations):
    # calculate the matrix-by-vector product Ab
    b_k1 = np.dot(A, b_k)
    # calculate the norm
    b_k1_norm = np.linalg.norm(b_k1)
    # re normalize the vector
    b_k = b_k1 / b_k1_norm

    ev_new = eigenvalue(A, b_k)
    print(_+1, 'st iteration eigenvalue:', ev_new)
    print(_+1, 'st iteration eigenvector:', b_k, '\n')
 return b_k

def eigenvalue(A, v):
    Av = A.dot(v)
    return v.dot(Av)

In [4]:
m1 = np.array([[2,-12],[1,-5]])
m2 = np.array([[1,2,0],[-2,1,2],[1,3,1]])

power_iteration(m1,5)
power_iteration(m2,5)

init eigenvector: [0.70710678 0.70710678] 

1 st iteration eigenvalue: -2.758620689655172
1 st iteration eigenvector: [-0.92847669 -0.37139068] 

2 st iteration eigenvalue: -2.2760180995475108
2 st iteration eigenvector: [0.94174191 0.3363364 ] 

3 st iteration eigenvalue: -2.1213973799126644
3 st iteration eigenvector: [-0.9456866  -0.32507977] 

4 st iteration eigenvalue: -2.0572482049291687
4 st iteration eigenvector: [0.94728103 0.32040388] 

5 st iteration eigenvalue: -2.027832546196526
5 st iteration eigenvector: [-0.94800398 -0.31825848] 

init eigenvector: [0.57735027 0.57735027 0.57735027] 

1 st iteration eigenvalue: 2.1428571428571423
1 st iteration eigenvector: [0.50709255 0.16903085 0.84515425] 

2 st iteration eigenvalue: 2.9298245614035086
2 st iteration eigenvector: [0.38235956 0.38235956 0.84119102] 

3 st iteration eigenvalue: 3.101694915254238
3 st iteration eigenvector: [0.39056673 0.4426423  0.80717125] 

4 st iteration eigenvalue: 3.0067553303778762
4 st iteration

array([0.41010447, 0.40452482, 0.81741911])

### b)

In [5]:
m3 = np.array([[1,1,0],[3,-1,0],[0,0,-2]])
power_iteration(m3,3)
# it didn't converge, beacuse m3 doesn't have eigenvalue and eigenvector.

init eigenvector: [0.57735027 0.57735027 0.57735027] 

1 st iteration eigenvalue: 0.6666666666666669
1 st iteration eigenvector: [ 0.57735027  0.57735027 -0.57735027] 

2 st iteration eigenvalue: 0.6666666666666666
2 st iteration eigenvector: [0.57735027 0.57735027 0.57735027] 

3 st iteration eigenvalue: 0.6666666666666666
3 st iteration eigenvector: [ 0.57735027  0.57735027 -0.57735027] 



array([ 0.57735027,  0.57735027, -0.57735027])

### c)

In [6]:
import numpy as np
def power_iteration_2 (A, num_simulations ):
 # Ideally choose a random vector
 # To decrease the chance that our vector
 # Is orthogonal to the eigenvector
 b_k = np.ones(A.shape[0])
 print('init:', b_k)
 for _ in range(num_simulations):
    # calculate the matrix-by-vector product Ab
    b_k1 = np.dot(A, b_k)
    print(b_k1)
    # calculate the norm
    b_k1_norm = max(b_k1)
    print(_+1, 'st iteration eigenvalue:',b_k1_norm)
    # re normalize the vector
    b_k = b_k1 / b_k1_norm

    print(_+1, 'st iteration eigenvector:', b_k, '\n')
 return b_k1_norm,b_k

In [7]:
m1 = np.array([[2,-12],[1,-5]])
power_iteration_2(m1,15)    

init: [1. 1.]
[-10.  -4.]
1 st iteration eigenvalue: -4.0
1 st iteration eigenvector: [2.5 1. ] 

[-7.  -2.5]
2 st iteration eigenvalue: -2.5
2 st iteration eigenvector: [2.8 1. ] 

[-6.4 -2.2]
3 st iteration eigenvalue: -2.2
3 st iteration eigenvector: [2.90909091 1.        ] 

[-6.18181818 -2.09090909]
4 st iteration eigenvalue: -2.090909090909091
4 st iteration eigenvector: [2.95652174 1.        ] 

[-6.08695652 -2.04347826]
5 st iteration eigenvalue: -2.043478260869565
5 st iteration eigenvector: [2.9787234 1.       ] 

[-6.04255319 -2.0212766 ]
6 st iteration eigenvalue: -2.0212765957446805
6 st iteration eigenvector: [2.98947368 1.        ] 

[-6.02105263 -2.01052632]
7 st iteration eigenvalue: -2.0105263157894737
7 st iteration eigenvector: [2.9947644 1.       ] 

[-6.0104712 -2.0052356]
8 st iteration eigenvalue: -2.005235602094241
8 st iteration eigenvector: [2.99738903 1.        ] 

[-6.00522193 -2.00261097]
9 st iteration eigenvalue: -2.0026109660574414
9 st iteration eigenv

(-2.0000406917599185, array([2.99997965, 1.        ]))

### d)

In [8]:
def power_iteration_3 (A):
 # Ideally choose a random vector
 # To decrease the chance that our vector
 # Is orthogonal to the eigenvector
 b_k = np.ones(A.shape[0])/ np.sqrt(A.shape[0])
 print('begin')
 i = 1
 while True:
    temp = b_k
    # calculate the matrix-by-vector product Ab
    b_k1 = np.dot(A, b_k)
    # calculate the norm
    b_k1_norm = np.linalg.norm(b_k1)
    # re normalize the vector
    b_k = b_k1 / b_k1_norm
    ev_new = eigenvalue(A, b_k)
    # print(i, 'st iteration: eigenvalue:', ev_new, '\n')
    # print(i, 'st iteration eigenvector:', b_k, '\n')
    if max(b_k - temp) < 0.001:
        print('end:', i ,'th iteration', '\n')
        break
    i += 1
 return b_k

In [9]:
m4 = np.array([[4,5],[6,5]])
m5 = np.array([[-4,10],[7,5]])

power_iteration_3(m4)
power_iteration_3(m5)

begin
end: 3 th iteration 

begin
end: 51 th iteration 



array([0.58059186, 0.81419475])

## EX. 4

### a)

In [10]:
L = [[2,-1,-1,0,0,0,0,0,0],
     [-1,3,-1,-1,0,0,0,0,0],
     [-1,-1,3,0,0,0,-1,0,0],
     [0,-1,0,3,-1,-1,0,0,0],
     [0,0,0,-1,2,-1,0,0,0],
     [0,0,0,-1,-1,3,0,-1,0],
     [0,0,-1,0,0,0,3,-1,-1],
     [0,0,0,0,0,-1,-1,3,-1],
     [0,0,0,0,0,0,-1,-1,2]
    ]

In [11]:
import numpy as np

L = np.array(L)

print(L.shape)
print(np.transpose(L) == L)

(9, 9)
[[ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]]


### b)

In [12]:
eigenvalue,featurevector=np.linalg.eig(L)

In [13]:
# print(eigenvalue.shape)
eigenvalue=np.round(eigenvalue, 5)
print(eigenvalue)
for i in range(9):
    print('index:',i, '\n',eigenvalue[i])

# three smalles index: 2,3,4
# three smallest eigenvalue: 0.69722, 0,  0.69722

[4.30278 3.      0.69722 0.      0.69722 3.      5.      4.30278 3.     ]
index: 0 
 4.30278
index: 1 
 3.0
index: 2 
 0.69722
index: 3 
 0.0
index: 4 
 0.69722
index: 5 
 3.0
index: 6 
 5.0
index: 7 
 4.30278
index: 8 
 3.0


In [14]:
print(featurevector.shape)
featurevector = np.round(featurevector, 3)
featurevector

(9, 9)


array([[ 0.315, -0.667, -0.588, -0.333, -0.149, -0.031,  0.   , -0.005,
        -0.032],
       [-0.362,  0.333, -0.383, -0.333,  0.017, -0.362,  0.408, -0.385,
        -0.297],
       [-0.362,  0.333, -0.383, -0.333, -0.211,  0.393, -0.408,  0.397,
         0.329],
       [ 0.519,  0.333,  0.089, -0.333,  0.401, -0.362, -0.408,  0.11 ,
        -0.297],
       [-0.157, -0.167,  0.294, -0.333,  0.567,  0.181,  0.   , -0.27 ,
         0.625],
       [-0.157, -0.167,  0.294, -0.333,  0.338,  0.181,  0.408,  0.512,
        -0.328],
       [ 0.519,  0.333,  0.089, -0.333, -0.355,  0.393,  0.408, -0.127,
         0.329],
       [-0.157, -0.167,  0.294, -0.333, -0.189,  0.181, -0.408, -0.506,
        -0.328],
       [-0.157, -0.167,  0.294, -0.333, -0.418, -0.574, -0.   ,  0.275,
        -0.001]])

In [15]:
#同一个特征值可对应多个特征向量，不同特征值对应的特征向量不相等
# three smalles index: 2,3,4
for i in range(9):
    if i == 2 or i == 3 or i == 4:
        print('one of the tree smallest eigenvalues eigenvector')
    print(featurevector[:,i],'\n')

[ 0.315 -0.362 -0.362  0.519 -0.157 -0.157  0.519 -0.157 -0.157] 

[-0.667  0.333  0.333  0.333 -0.167 -0.167  0.333 -0.167 -0.167] 

one of the tree smallest eigenvalues eigenvector
[-0.588 -0.383 -0.383  0.089  0.294  0.294  0.089  0.294  0.294] 

one of the tree smallest eigenvalues eigenvector
[-0.333 -0.333 -0.333 -0.333 -0.333 -0.333 -0.333 -0.333 -0.333] 

one of the tree smallest eigenvalues eigenvector
[-0.149  0.017 -0.211  0.401  0.567  0.338 -0.355 -0.189 -0.418] 

[-0.031 -0.362  0.393 -0.362  0.181  0.181  0.393  0.181 -0.574] 

[ 0.     0.408 -0.408 -0.408  0.     0.408  0.408 -0.408 -0.   ] 

[-0.005 -0.385  0.397  0.11  -0.27   0.512 -0.127 -0.506  0.275] 

[-0.032 -0.297  0.329 -0.297  0.625 -0.328  0.329 -0.328 -0.001] 



In [16]:
## test
# X=[[-1,1,0],
# [-4,3,0],
# [1,0,2]]
# X = np.array(X)
# eigenvalue,featurevector=np.linalg.eig(X)
# print ("eigenvalue=",eigenvalue)
# print("featurevector=",featurevector[:,0])

### c)

In [17]:
#Compute orthonormal matrix U whose columns are eigenvectors to the k smallest eigenvalues of L
U = np.array([featurevector[:,3],featurevector[:,2],featurevector[:,4]]).T
U

array([[-0.333, -0.588, -0.149],
       [-0.333, -0.383,  0.017],
       [-0.333, -0.383, -0.211],
       [-0.333,  0.089,  0.401],
       [-0.333,  0.294,  0.567],
       [-0.333,  0.294,  0.338],
       [-0.333,  0.089, -0.355],
       [-0.333,  0.294, -0.189],
       [-0.333,  0.294, -0.418]])

In [18]:
# let x1,...xn  be the rows of U
# cluster x1... xn using k-means, yielding clusters C1...Ck
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=3, random_state=0)
kmeans.fit(U)
print(kmeans.labels_)
for i,j in enumerate(kmeans.labels_):
    if j == 0:
        print(i+1, 'belongs to cluster',j)
    elif j == 1:
        print(i+1, 'belongs to cluster',j)
    elif j == 2:
        print(i+1, 'belongs to cluster',j)

[2 2 2 0 0 0 1 1 1]
1 belongs to cluster 2
2 belongs to cluster 2
3 belongs to cluster 2
4 belongs to cluster 0
5 belongs to cluster 0
6 belongs to cluster 0
7 belongs to cluster 1
8 belongs to cluster 1
9 belongs to cluster 1
